// Canonical Economics 101 data for prerendering.
export const WEEK_META = {
  1: { title: "Week 1 — Foundations: scarcity, trade, and markets", summary: "What economics is and why it exists; the production possibilities frontier; comparative advantage and trade; supply and demand; market equilibrium; elasticity; price controls and taxes.", metaDescription: "Scarcity, opportunity cost, trade, supply, demand, equilibrium, elasticity, controls, and taxes." },
  2: { title: "Week 2 — Consumers, firms, and market structure", summary: "Consumer choice and utility; consumer and producer surplus; production and costs; perfect competition; monopoly; oligopoly and game theory; externalities and public goods.", metaDescription: "Consumers, firms, market structure, strategic behavior, externalities, and public goods." },
  3: { title: "Week 3 — Macroeconomics: output, prices, and money", summary: "Measuring GDP; inflation and price indices; unemployment; long-run economic growth; money and banking; aggregate demand and aggregate supply; business cycles.", metaDescription: "GDP, inflation, unemployment, growth, money, aggregate demand, supply, and cycles." },
  4: { title: "Week 4 — Macroeconomic policy and the open economy", summary: "Fiscal policy and the multiplier; monetary policy and central banking; the Phillips curve and expectations; exchange rates and purchasing power parity; the balance of payments; international trade policy; government debt and deficits; a capstone synthesis.", metaDescription: "Fiscal and monetary policy, expectations, exchange rates, trade, debt, and the open economy." },
};
const rows = [
["what-is-economics",1,"What economics is and why it exists","Economics exists because wants are unlimited and resources are not.","Economics studies allocation under scarcity. Opportunity cost is the value of the best alternative forgone; rational choice compares marginal benefit and marginal cost. Every economic system decides what, how, and for whom to produce."],
["production-possibilities-frontier",1,"The production possibilities frontier","The menu of what an economy can produce, and the cost of moving along it.","The PPF gives maximum combinations with current resources and technology. Points inside are inefficient, points outside unattainable, and movement along it has OC_X = −ΔY/ΔX. Growth shifts the frontier outward."],
["comparative-advantage-trade",1,"Comparative advantage and trade","Trade pays whenever opportunity costs differ — even if one side is better at everything.","Comparative advantage means lower opportunity cost, not necessarily absolute productivity. Specialization and terms of trade between opportunity costs let both countries consume more, though trade redistributes gains."],
["supply-demand",1,"Supply and demand","Two curves that summarize every buyer and every seller in a market.","Demand Q_d=a−bP slopes down and supply Q_s=c+dP slopes up. Own-price changes move along curves; income, tastes, substitutes, technology, input prices, expectations, and participant counts shift them."],
["market-equilibrium",1,"Market equilibrium","Where the curves cross, and how markets get there.","Equilibrium solves Q_d(P*)=Q_s(P*); linear curves give P*=(a−c)/(b+d). Shortages below equilibrium bid price up, while surpluses above it push price down."],
["elasticity",1,"Elasticity","How strongly quantity responds to price.","E_d=%ΔQ_d/%ΔP; the midpoint formula avoids base dependence. Substitutes, luxuries, large budget shares, and long horizons increase elasticity, which determines how price changes affect revenue."],
["price-controls-taxes",1,"Price controls and taxes","What happens when government overrides the market price.","A binding ceiling creates shortage and a binding floor creates surplus. Taxes create P_b−P_s=t; the less elastic side bears more, and DWL=½·t·ΔQ."],
["consumer-choice-utility",2,"Consumer choice and utility","How a budget-constrained consumer picks the best bundle.","The budget is P_xX+P_yY=I. Utility is maximized where MU_x/P_x=MU_y/P_y (MRS=P_x/P_y). Diminishing marginal utility and substitution and income effects explain demand."],
["consumer-producer-surplus",2,"Consumer and producer surplus","Measuring the gains from trade in dollars.","CS=½(P_max−P*)Q* and PS=½(P*−P_min)Q*. Their sum is total surplus; competitive equilibrium maximizes gains when private and social marginal values agree."],
["production-costs",2,"Production and costs","From inputs to output, and what each unit costs.","Q=f(K,L), TC=FC+VC, ATC=TC/Q, and MC=ΔTC/ΔQ. Diminishing returns raise marginal cost; economies and diseconomies of scale determine efficient industry size."],
["perfect-competition",2,"Perfect competition","Many firms, identical products, and price equal to marginal cost.","Price-taking firms maximize π=TR−TC where P=MR=MC and shut down below AVC. Entry and exit produce long-run P=MC=min ATC and zero economic profit."],
["monopoly",2,"Monopoly","A single seller facing the whole demand curve.","A monopolist chooses MR=MC and charges demand price. The Lerner index is (P−MC)/P=−1/E_d; restricted output creates deadweight loss and motivates antitrust or regulation."],
["oligopoly-game-theory",2,"Oligopoly and game theory","When a few firms must anticipate each other's moves.","Interdependent firms use game theory. Nash equilibrium makes no player want unilateral change; the prisoner's dilemma explains why collusion is collectively profitable but individually unstable."],
["externalities-public-goods",2,"Externalities and public goods","When markets misprice costs and benefits that fall on others.","For pollution SMC=PMC+MEC. Pigouvian taxes, cap-and-trade, and Coase bargaining can internalize external costs. Nonrival, nonexcludable public goods invite free riding and underprovision."],
["measuring-gdp",3,"Measuring GDP","The market value of everything an economy produces.","GDP can be measured by spending: Y=C+I+G+NX. Nominal GDP uses current prices, real GDP constant prices, and the deflator=(nominal/real)×100. GDP omits many welfare dimensions."],
["inflation-price-indices",3,"Inflation and price indices","Tracking the rising cost of living.","CPI_t=(basket_t/basket_base)×100 and π_t=(CPI_t−CPI_t−1)/CPI_t−1. Fixed baskets miss substitution and quality changes; inflation creates menu, shoe-leather, redistribution, and information costs."],
["unemployment",3,"Unemployment","Who counts as unemployed, and why it never reaches zero.","u=U/(U+E)×100 and LFPR=(U+E)/adult population×100. Frictional, structural, and cyclical unemployment differ; the natural rate is frictional plus structural."],
["long-run-growth",3,"Long-run economic growth","Why some countries are rich and others poor.","Y=AK^αL^(1−α) and g_Y=g_A+αg_K+(1−α)g_L. Capital has diminishing returns, so lasting per-person growth requires productivity, technology, education, and institutions."],
["money-banking",3,"Money and banking","What money is, how banks create it, and how it relates to prices.","Money is exchange medium, account unit, and store of value. The simple reserve multiplier is m=1/rr; quantity theory MV=PY and π≈g_M+g_V−g_Y connect money to prices."],
["aggregate-demand-supply",3,"Aggregate demand and aggregate supply","The workhorse model of output and the price level.","AD is Y=C+I+G+NX; short-run AS slopes up with sticky prices and long-run AS is vertical at Y*. Demand shocks move output and prices together; adverse supply shocks trade output for inflation."],
["business-cycles",3,"Business cycles","The recurring rise and fall of economic activity.","Expansions, peaks, contractions, and troughs move output around trend. The output gap=(Y−Y*)/Y*×100; demand swings, productivity shocks, and financial accelerators explain cycles."],
["fiscal-policy-multiplier",4,"Fiscal policy and the multiplier","Government spending and taxes as tools for stabilizing output.","k=1/(1−MPC) and k_T=−MPC/(1−MPC). Leakages, imports, crowding out, and expectations make real multipliers smaller; automatic stabilizers work without new laws."],
["monetary-policy-central-banking",4,"Monetary policy and central banking","How the central bank steers interest rates, credit, and inflation.","Central banks set rates and trade securities. Taylor rule i=r*+π+0.5(π−π*)+0.5(Y−Y*)/Y*. Higher rates reduce demand through long, variable lags."],
["phillips-curve-expectations",4,"The Phillips curve and expectations","The short-run tradeoff between inflation and unemployment — and why it vanishes.","π=π^e−β(u−u_n) describes a short-run surprise tradeoff. Once expectations adapt, unemployment returns to its natural rate and the long-run curve is vertical."],
["exchange-rates-ppp",4,"Exchange rates and purchasing power parity","The price of one currency in terms of another.","ε=eP/P* and PPP implies e=P*/P. Relative PPP predicts %Δe≈π*−π, though transport costs, nontradables, tariffs, and capital flows create short-run gaps."],
["balance-of-payments",4,"The balance of payments","The accounting of a nation's transactions with the rest of the world.","Current and financial accounts sum to zero. From Y=C+I+G+NX, national saving gives NX=S−I: investment beyond domestic saving is financed by foreign capital."],
["international-trade-policy",4,"International trade policy","Tariffs, quotas, and who pays for protection.","A tariff raises domestic price, benefits producers, costs consumers, collects t×M, and creates DWL=½t(ΔQ_s+ΔQ_d). Concentrated benefits and diffuse costs explain protection."],
["government-debt-deficits",4,"Government debt and deficits","How public debt evolves and when it becomes a problem.","Debt dynamics are Δb≈(r−g)b−s. If r<g, modest primary deficits can be sustainable; high debt may crowd out investment, raise taxes, or trigger a confidence spiral."],
["capstone-synthesis",4,"Capstone synthesis","One principle behind everything: optimizing agents meeting in equilibrium.","Economic outcomes arise from marginal choices meeting in equilibrium. MB=MC links consumer utility, firm MR=MC, market clearing, macro policy, and the market failures that justify intervention."]
];
export const TOPICS = rows.map(([slug,weekNumber,title,blurb,body],i)=>({slug,weekNumber,blurb,metaDescription:blurb,lectureTitle:`${weekNumber}.${i%7+1} ${title}`,body:`# ${title}\n\n${body}`}));